### ISSUE TITLE
CK metric: from tree to vector

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/exploratree#3]
Ideally, we would want a function taking a phylo object as input, plus optional parameters, and outputting a labelled vector of numbers.

Sorry if it is there already - may need to go through the implementation together ;)

**Comment by MichelleKendall** [comment]
Sure, I'll do that for the topological metric now. 

For the weighted metric it's a bit more tricky. I'll see if I can explain here, but if not I can go through it with you in person: we need to have two vectors (x=(x1,...,xn) and y=(y1,...,yn) ) and a constant (espilon) per tree - obviously you could store that all as one vector v=(x1,...,xn,y1,...,yn,epsilon) but when you're doing the Euclidean distances it can't just be the Euc distance between the v vectors of two trees. They need to be handled separately, that is, find the Euc dist between the x vectors, add the Euc dist between the y vectors, and finally add the absolute value of the difference in epsilons, divided by number of tips.

**Comment by MichelleKendall** [comment]
# function to take ONE object of class phylo and return its topological vector
top.vec <- function(tr1) {
  k <- length(tr1$tip.label)
  # checks and warnings
    
  # set all edge lengths to 1:
  tr1$edge.length <- rep(1,(2*k-2));
  # create vector of distances from root to tips:
  DN1 <- dist.nodes(tr1)[k+1,];
  # create mrca matrix:
  M1 <- my.mrca(tr1,k);
  
  # calculate the gamma vector of root to mrca distances:
  gamma <- apply(combn2(1:k), 1, function(x) DN1[M1[[x[1],x[2]]]]) 
  
  return(gamma)
}
# compile:
top.vec <- cmpfun(top.vec)

**Comment by MichelleKendall** [comment]
# function to take ONE object of class phylo and return one long weighted vector
  # caveat: a tree should not be compared to another tree simply by taking the Euclidean distance between their vectors output by this function
w.vec <- function(tr1,p=1) {
  k <- length(tr1$tip.label)
  # checks and warnings
  if (is.null(tr1$edge.length)) {
    stop("edge lengths not defined")
  }
    
  tr1$edge.length <- tr1$edge.length + p;
  
  DN1 <- dist.nodes(tr1);
  M1 <- my.mrca(tr1,k);
  
  pairs <-combn2(1:k);  
  gamma <- apply(pairs, 1, function(x) DN1[k+1,M1[[x[1],x[2]]]]) 
  delta <- apply(pairs, 1, function(x) DN1[k+1,x[1]]-DN1[k+1,x[2]])
  
    # add minimum pendant branch length / k
  ep1 <- edge.pendant(tr1,k);
  pen.length1 <- apply(ep1, 1, function(x) DN1[x[1],x[2]])
  near1 <- min(pen.length1)/k;
  
  v <- c(gamma,delta,near1)
  return(v)
}
w.vec <- cmpfun(w.vec)

**Comment by thibautjombart** [comment]
Awesome!
Do you want to add it to /R/metric.R?
Happy to help with GIT if useful ;)
Cheers
Thibaut

**Comment by MichelleKendall** [comment]
Aha! Yes, sorry, I hadn't realised I could do that. Added now :)

Michelle

**Comment by thibautjombart** [comment]
Is now the function CK.metric as of aa156c0e1cb
