### ISSUE TITLE
Add dataset(s) to the package

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/exploratree#5]
We need publicly available / release-able data to illustrate the method.

**Comment by MichelleKendall** [comment]
Yes. Any ideas, Caroline? I've been using the "woodmouse" data example that comes with R for simple tests - I expect we could come up with something more interesting, but in the meantime you could do something like this:

data(woodmouse)
otree <- root(nj(dist.dna(woodmouse)), "No305", resolve.root=TRUE)
breps = 100
trees <- boot.phylo(otree, woodmouse, B=breps, function(x) root(nj(dist.dna(x)), "No305", resolve.root=TRUE),trees=TRUE)
combined.trees <- c(list(otree), trees$trees)
class(combined.trees)<- "multiPhylo"
tree.dists <- CK.gdistm(combined.trees)
mdres <- cmdscale(tree.dists, k=2, add=TRUE)
plot(mdres$points[,1], mdres$points[,2], xlab="", ylab="")

**Comment by MichelleKendall** [comment]
I have created an example using 201 woodmice trees created (pretty much) as above. They contain islands, which demonstrates the method nicely I think. See example(multi.dist) or do data(woodmiceTrees) to access the trees. 

I am, however, getting a couple of warnings about it which I don't understand:
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  'woodmiceTrees'
Undocumented data sets:
  'woodmiceTrees'

**Comment by MichelleKendall** [comment]
Sorted: I had the wrong alias, and a non-ASCII character.
